name: Deploy Shared Resources

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ deploy_shared ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Private Code
      uses: actions/checkout@v6
      with:
        repository: ${{ secrets.INRFA_CODE_REPO }}
        ref: main
        token: ${{ secrets.GHA_PAT }}

    - name: Prepare directory structure
      run: mv caddy/config caddy_config

    - name: Copy Files to Server
      uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ".,!.git,!scripts"
        target: "/opt/gha-deployment"
        overwrite: true

    - name: Deploy Stack
      uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
      with:
        host: ${{ secrets.SERVER_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /opt/gha-deployment

          docker compose -f shared.yml up -d
          docker image prune -f
          # rm -rf .env
