run-name: Deploy ${{github.event.client_payload.app }} from ${{ github.event.client_payload.branch }}
name: Deploy

on:
  repository_dispatch:
    types: [deploy_request]

jobs:
  build-frontend:
    if: ${{ github.event.client_payload.app == 'PTL-fe' }}
    uses: ./.github/workflows/feBuildAndPublish.yml
    with:
      environment: ${{ github.event.client_payload.branch }}
    secrets: inherit

  build-backend:
    if: ${{ github.event.client_payload.app == 'PTL-be' }}
    uses: ./.github/workflows/beBuildAndPublish.yml
    with:
      environment: ${{ github.event.client_payload.branch }}
    secrets: inherit

  deploy:
    needs: [build-frontend, build-backend]
    environment: ${{ github.event.client_payload.branch == 'main' && 'prod' || 'dev' }}
    if: |
      always() &&
      (needs.build-frontend.result == 'success' || needs.build-backend.result == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Code
        uses: actions/checkout@v6
        with:
          repository: ${{ secrets.INRFA_CODE_REPO }}
          ref: main
          token: ${{ secrets.PAT_TOKEN }}

      - name: Copy Files to Server
        uses: appleboy/scp-action@ff85246acaad7bdce478db94a363cd2bf7c90345
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/opt/gha-deployment"
          exclude: ".git,.github"

      - name: Deploy Stack
        uses: appleboy/ssh-action@0ff4204d59e8e51228ff73bce53f80d53301dee2
        env:
          DEPLOY_ENV: ${{ github.event.client_payload.branch == 'main' && 'prod' || 'dev' }}
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DEPLOY_ENV
          script: |
            cd /opt/gha-deployment

            # Determine compose file
            if [ "$DEPLOY_ENV" = "prod" ]; then
              COMPOSE_FILE="prod.yml"
            else
              COMPOSE_FILE="dev.yml"
            fi

            echo "Deploying using $COMPOSE_FILE..."

            cat <<EOF > .env
            DB_HOST=${{ secrets.DB_HOST }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_SIE_USER=${{ secrets.DB_SIE_USER }}
            DB_SIE_PASSWORD=${{ secrets.DB_SIE_PASSWORD }}
            DB_SIE_NAME=${{ secrets.DB_SIE_NAME }}

            EMAIL_HOST=${{ secrets.EMAIL_HOST }}
            EMAIL_PORT=${{ secrets.EMAIL_PORT }}
            EMAIL_USER=${{ secrets.EMAIL_USER }}
            EMAIL_PASS=${{ secrets.EMAIL_PASS }}
            RECEIVER_EMAIL=${{ secrets.RECEIVER_EMAIL }}
            SALES_EMAIL_USER=${{ secrets.SALES_EMAIL_USER }}
            SALES_EMAIL_PASS=${{ secrets.SALES_EMAIL_PASS }}

            PAYU_MERCHANT_POS_ID=${{ secrets.PAYU_MERCHANT_POS_ID }}
            PAYU_OAUTH_CLIENT_ID=${{ secrets.PAYU_OAUTH_CLIENT_ID }}
            PAYU_SECOND_KEY_MD5=${{ secrets.PAYU_SECOND_KEY_MD5 }}
            PAYU_OAUTH_CLIENT_SECRET=${{ secrets.PAYU_OAUTH_CLIENT_SECRET }}
            PAYU_OAUTH_URL=${{ secrets.PAYU_OAUTH_URL }}
            PAYU_ORDER_URL=${{ secrets.PAYU_ORDER_URL }}

            GOOGLE_PLACE_ID=${{ secrets.GOOGLE_PLACE_ID }}
            GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}

            API_KEY=${{ secrets.API_KEY }}
            HMAC_SECRET=${{ secrets.HMAC_SECRET }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            EOF

            chmod 600 .env

            docker compose -f $COMPOSE_FILE pull
            docker compose -f $COMPOSE_FILE up -d
            docker image prune -f
            rm -rf .env
